const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const today=()=>new Date().toISOString().slice(0,10), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const get=(k)=>{try{return JSON.parse(localStorage.getItem(k))||[]}catch{return[]}}, set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let trades=get('tt_trades'), costs=get('tt_investments'), payouts=get('tt_payouts'), shot='', view='Daily', month=today().slice(0,7);
$$('input[type=date]').forEach(x=>x.value=today()); $('#monthPicker').value=month;
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tabPage').forEach(x=>x.hidden=true);$('#'+b.dataset.tab).hidden=false;render()});
$('#screenshot').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{shot=r.result;$('#preview').src=shot;$('#preview').hidden=false};r.readAsDataURL(f)};
$('#tradeForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);trades.unshift({id:crypto.randomUUID(),date:f.get('date'),symbol:f.get('symbol'),direction:f.get('direction'),pnl:Number(f.get('pnl')),entry:f.get('entry'),exit:f.get('exit'),quantity:f.get('quantity'),mood:f.get('mood'),details:f.get('details'),screenshot:shot});set('tt_trades',trades);const date=f.get('date');e.target.reset();e.target.date.value=date;e.target.mood.value='Calm';shot='';$('#preview').hidden=true;render()};
$('#costForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);costs.unshift({id:crypto.randomUUID(),firm:f.get('firm'),cost:Number(f.get('cost')),date:f.get('date'),type:f.get('type')});set('tt_investments',costs);e.target.reset();e.target.date.value=today();render()};
$('#payoutForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);payouts.unshift({id:crypto.randomUUID(),firm:f.get('firm'),total:Number(f.get('total')),date:f.get('date')});set('tt_payouts',payouts);e.target.reset();e.target.date.value=today();render()};
function del(kind,id){if(kind==='trade'){trades=trades.filter(x=>x.id!==id);set('tt_trades',trades)}if(kind==='cost'){costs=costs.filter(x=>x.id!==id);set('tt_investments',costs)}if(kind==='payout'){payouts=payouts.filter(x=>x.id!==id);set('tt_payouts',payouts)}render()}
$$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;$$('[data-view]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');renderCalendar()});
$('#monthPicker').onchange=e=>{month=e.target.value;renderCalendar()}; function moveMonth(n){const d=new Date(month+'-15T12:00:00');d.setMonth(d.getMonth()+n);month=d.toISOString().slice(0,7);$('#monthPicker').value=month;renderCalendar()} $('#prevMonth').onclick=()=>moveMonth(-1);$('#nextMonth').onclick=()=>moveMonth(1);
function weekStart(s){const d=new Date(s+'T12:00:00'),day=d.getDay();d.setDate(d.getDate()+(day===0?-6:1-day));return d.toISOString().slice(0,10)}
function renderTrades(){const net=trades.reduce((s,x)=>s+x.pnl,0);$('#netPL').textContent=money(net);$('#netPL').className=net>=0?'positiveText':'negativeText';$('#tradeCount').textContent=`${trades.length} saved entries`;$('#tradeList').innerHTML=trades.length?trades.map(t=>`<article class="tradeRow"><div class="statusDot ${t.pnl>=0?'green':'red'}"></div><div class="grow"><strong>${t.symbol||'Untitled trade'} · ${t.direction}</strong><span>${t.date} · ${t.mood} · Qty ${t.quantity||'—'}</span>${t.details?`<p>${t.details}</p>`:''}${t.screenshot?`<img class="thumb" src="${t.screenshot}" alt="Trade screenshot">`:''}</div><div class="${t.pnl>=0?'positiveText':'negativeText'}"><strong>${money(t.pnl)}</strong><button class="delete" onclick="del('trade','${t.id}')">Delete</button></div></article>`).join(''):'<div class="empty">Your saved trades will appear here.</div>'}
function renderCalendar(){const daily={};trades.forEach(t=>{daily[t.date]??={pnl:0,count:0};daily[t.date].pnl+=t.pnl;daily[t.date].count++});const [y,m]=month.split('-').map(Number),first=new Date(y,m-1,1),last=new Date(y,m,0),pad=(first.getDay()+6)%7,cells=Array(pad).fill(null);for(let d=1;d<=last.getDate();d++)cells.push(`${month}-${String(d).padStart(2,'0')}`);while(cells.length%7)cells.push(null);$('#calendarGrid').innerHTML=cells.map(date=>{if(!date)return'<div class="day"></div>';const x=daily[date];return`<div class="day ${x?(x.pnl>=0?'profitDay':'lossDay'):''}"><b>${Number(date.slice(-2))}</b>${x?`<span>${x.count} trade${x.count!==1?'s':''}</span><strong>${money(x.pnl)}</strong>`:''}</div>`}).join('');const periods={};trades.forEach(t=>{const k=view==='Daily'?t.date:view==='Weekly'?weekStart(t.date):t.date.slice(0,7);periods[k]??={pnl:0,count:0};periods[k].pnl+=t.pnl;periods[k].count++});$('#periodTitle').textContent=view+' Totals';const rows=Object.entries(periods).sort((a,b)=>b[0].localeCompare(a[0]));$('#periodList').innerHTML=rows.length?rows.map(([k,x])=>`<div class="summaryRow"><div><strong>${k}</strong><span>${x.count} total trades</span></div><strong class="${x.pnl>=0?'positiveText':'negativeText'}">${money(x.pnl)}</strong></div>`).join(''):'<div class="empty">No performance data yet.</div>'}
function renderFinance(){const nt=costs.filter(x=>x.type==='NEW').reduce((s,x)=>s+x.cost,0),rt=costs.filter(x=>x.type==='RESET').reduce((s,x)=>s+x.cost,0),pt=payouts.reduce((s,x)=>s+x.total,0);$('#newTotal').textContent=money(nt);$('#resetTotal').textContent=money(rt);$('#payoutTotal').textContent=money(pt);const rows=[...costs.map(x=>({...x,kind:'cost',amount:x.cost})),...payouts.map(x=>({...x,kind:'payout',amount:x.total}))].sort((a,b)=>b.date.localeCompare(a.date));$('#financeList').innerHTML=rows.length?rows.map(x=>`<div class="summaryRow"><div><strong>${x.firm}</strong><span>${x.date} · ${x.kind==='payout'?'PAYOUT':x.type}</span></div><div class="${x.kind==='payout'?'positiveText':'negativeText'}"><strong>${x.kind==='payout'?'+':'-'}${money(x.amount)}</strong><button class="delete" onclick="del('${x.kind}','${x.id}')">Delete</button></div></div>`).join(''):'<div class="empty">Costs and payouts will appear here.</div>'}
function render(){renderTrades();renderCalendar();renderFinance()} render();
